# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: ThePorch
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}

CONTENTFUL:
  PORCH:
    SPACE: 3ewlji0hjgzj
    API_KEY: ${CONTENTFUL_PORCH_KEY}
  CONFERENCE:
    SPACE: 3ewlji0hjgzj
    API_KEY: ${CONTENTFUL_PORCH_KEY}

BUGSNAG:
  ## Optional, but you'll need to remove references to @apollosproject/bugsnag if you don't wish to use.
  API_KEY: 7ffed442dcec30138c5ea7cbdfd72698

ROCK:
  API_URL: https://rock.theporch.live/api
  API_TOKEN: ${ROCK_TOKEN}
  IMAGE_URL: https://rock.theporch.live/GetImage.ashx
  SHARE_URL: https://wcc-theporch-app.herokuapp.com
  # This should match the timezone of the Rock server
  TIMEZONE: 'America/New_York'
  USE_PLUGIN: true
  SHOW_INACTIVE_CONTENT: ${ROCK_SHOW_INACTIVE_CONTENT}

ONE_SIGNAL:
  APP_ID: 977d590f-3563-4291-8105-ff1495cef4da
  REST_KEY: ${ONE_SIGNAL_REST_KEY}

UNIVERSAL_LINKS:
  # This should be your app's bundle ID, as found in your info.plist.
  APPLE_APP_ID: com.subsplashconsulting.8XHRPK
  # This should be your app's team ID, as found in Xcode
  APPLE_TEAM_ID: 5Z8S3JU749
  # Where should a user be redirected if they don't have your app installed?
  APP_STORE_LINK: https://apps.apple.com/us/app/the-porch/id908788854
  PLAY_STORE_LINK: https://apollos.app/android
  # Your app Id, as found in your app/build.gradle.
  GOOGLE_APP_ID:
  # https://docs.getsocial.im/knowledge-base/android-signing-key-sha256/
  GOOGLE_KEYSTORE_SHA256: EC:6E:B5:5A:62:53:1E:53:FF:C4:BA:A7:CB:29:77:57:71:9D:65:2F:AF:69:41:A3:AD:2B:C4:55:A1:7A:07:03
CHURCH_ONLINE:
  URL: https://apollos.churchonline.org/api/v1/
  MEDIA_URLS: []
  WEB_VIEW_URL: https://apollos.churchonline.org/
WATERMARK:
  MEDIA_API: https://media.watermark.org
ALGOLIA:
  APPLICATION_ID: FPTWE3M1PT
  API_KEY: ${ALGOLIA_API_KEY}
  # TODO: should we support multiple indices? how
  BLOG_INDEX: papyrus_heroku-production_blogs
  PEOPLE_INDEX: people_production
  MESSAGES_INDEX: Messages_production_rev_chron
  MESSAGES_POPULAR_INDEX: messages_production_trending
  MESSAGES_TOPIC_RANKED_INDEX: porchapp_production_messages_force_ranked
  # Configure Algolia custom settings here
  # https://www.algolia.com/doc/api-reference/settings-api-parameters/
  CONFIGURATION:
    searchableAttributes:
      - title
      - unordered(summary)
    #customRankings:
    # NOT CURRENTLY INCLUDED
    # This just demonstrates what's possible
    # To include likedCount (or any other field) override search package
    # and add field to config below
    #- desc(likedCount)
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
ANALYTICS:
  # Filling out these fields will automatically enable analytics tracking
  # on the accompanying service
  SEGMENT_KEY:
  GA_ID:
  USE_ROCK: true
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  BIBLE_ID:
    WEB: '9879dbb7cfe39e4d-01'
    KJV: 'de4e12af7f28f599-02'
CLOUDINARY:
  # Cloudinary is used to improve image loading
  # value should look something like
  # cloudinary://123123123:adkfnla_adASDv_adAS@test
  URL: ${CLOUDINARY_URL}
ENGINE:
  API_KEY: ${ENGINE_API_KEY}
  SCHEMA_TAG: ${ENGINE_SCHEMA_TAG}

# This key holds various properties that allow our GraphQL server to map to your Rock Instance
ROCK_MAPPINGS:
  INTERACTIONS:
    # Name of the InteractionChannel that will be created per EntityType
    CHANNEL_NAME: Apollos App
    # Prefix for the name of the InteractionComponent that will be created per Entity
    COMPONENT_NAME: Apollos App Component
    # 512 is "Mobile App"
    CHANNEL_MEDIUM_TYPE_ID: 512

  CONTENT_ITEM:
    ContentSeriesContentItem:
      # When resolving "ContentSeriesContentItem" look in rock for a "ContentChannelItem"
      EntityType: ContentChannelItem
      # Used to define the subset of content channels types that use this specific type.
      ContentChannelTypeId: [6, 7]
    DevotionalContentItem:
      EntityType: ContentChannelItem
      ContentChannelTypeId: [1]
    MediaContentItem:
      EntityType: ContentChannelItem
    WCCMessage:
      EntityType: ContentChannelItem
    WCCBlog:
      EntityType: ContentChannelItem
    WCCSeries:
      EntityType: ContentChannelItem
    LiveStream:
      EntityType: ContentChannelItem
    WCCSpeaker:
      EntityType: ContentChannelItem
    UniversalContentItem:
      EntityType: ContentChannelItem
    WeekendContentItem:
      ContentChannelId: [5]
      EntityType: ContentChannelItem
    Event:
      EntityType: Contentful
    Breakouts:
      EntityType: Contentful
    Location:
      EntityType: Contentful
    Speaker:
      EntityType: Contentful
    Announcement:
      EntityType: Contentful
    ContentItem:
      EntityType: Contentful

  DATAVIEW_CATEGORIES:
    # Id of the category used to store all persona dataviews
    PersonaId: 210

  # Apollos will pull these content channels and expose them in the app on the discover screen.
  DISCOVER_CONTENT_CHANNEL_IDS:
    - 2
    - 3
    - 4
    - 6
    - 8
  # Apollos will pull content items from these channels and expose them on the user feed
  # However, it will not expose the channel itself.
  # These channels are also pulled when indexing searchable content.
  FEED_CONTENT_CHANNEL_IDS:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 8

  CAMPAIGN_CHANNEL_IDS:
    - 11

  SERMON_CHANNEL_ID: 5

  SERVING_GROUP_TYPE_ID: 23
  COMMUNITY_GROUP_TYPE_ID: 25
  FAMILY_GROUP_TYPE_ID: 10

  MOBILE_DEVICE_TYPE_ID: 671

HOME_FEATURES:
  - type: ActionBar
  - algorithms:
      - type: CAMPAIGN_ITEMS
        arguments:
          limit: 1
    type: VerticalCardList
    isFeatured: true
  - subtitle: Your Porch Location
    algorithms: [CAMPUS_ITEMS]
    type: ActionList
    primaryAction:
      action: OPEN_CAMPUS # Implemented as a resolver, which creates a relatedNode of Url
      title: 'More info'
  - algorithms:
      - type: CAMPAIGN_ITEMS
        arguments:
          limit: 3
          skip: 1
    type: VerticalCardList
    isFeatured: false
  - heroAlgorithms:
      - type: WCC_SERIES
        arguments:
          seriesId: 562
    algorithms:
      - type: WCC_MESSAGES
        arguments:
          filters:
            filter[series_id][]: 562
    type: HeroList
  - algorithms: [USER_FEED]
    subtitle: From the Blog
    type: ActionList
    primaryAction:
      action: OPEN_CONTENT_CHANNEL
      title: 'View More'
      relatedNode:
        __typename: ContentChannel
        id: 'https://di0v2frwtdqnv.cloudfront.net/api/v1/property/theporch-app'
        name: 'From the Blog'

DISCOVER_FEATURES:
  - algorithms:
      - type: CONTENT_CHANNEL_CHILDREN
        arguments:
          id: '{"search":"messages_production_trending","name":"Crowd Favorites","filters":"ministries:\"The Porch\""}'
          limit: 3
    type: ActionList
    subtitle: Crowd Favorites
    primaryAction:
      action: OPEN_CHANNEL
      title: 'View More'
      relatedNode:
        __typename: ContentChannel
        id: '{"search":"messages_production_trending","name":"Crowd Favorites","filters":"ministries:\"The Porch\""}'
        name: Crowd Favorites
  - algorithms:
      - type: CONTENT_CHANNELS
        arguments:
          ids:
            - 852
            - 665
            - 581
            - 510
            - 457
            - 406
            - 342
          limit: 7
    type: ActionList
    subtitle: Top Series' on Dating
  - algorithms:
      - type: CONTENT_CHANNEL_CHILDREN
        arguments:
          id: 'https://media.watermark.org/api/v1/series?filter[tag_id]=4'
          limit: 3
    type: HorizontalCardList
    subtitle: Series
    primaryAction:
      action: OPEN_CHANNEL
      title: 'View More'
      relatedNode:
        __typename: ContentChannel
        id: 'https://media.watermark.org/api/v1/series?filter[tag_id]=4'
        name: Series
  - algorithms:
      - type: CONTENT_CHANNEL_CHILDREN
        arguments:
          id: '{"search":"porchapp_production_messages_force_ranked","name":"Anxiety","query":"topic_anxiety","filters":"ministries:\"The Porch\" AND topics:\"Anxiety\""}'
          limit: 5
    type: ActionList
    subtitle: Anxiety
    primaryAction:
      action: OPEN_CHANNEL
      title: 'View More'
      relatedNode:
        __typename: ContentChannel
        id: '{"search":"porchapp_production_messages_force_ranked","name":"Anxiety","query":"topic_anxiety","filters":"ministries:\"The Porch\" AND topics:\"Anxiety\""}'
        name: Anxiety
  - algorithms:
      - type: CONTENT_CHANNEL_CHILDREN
        arguments:
          id: '{"search":"porchapp_production_messages_force_ranked","name":"Books of the Bible","query":"topic_books_of_the_bible","filters":"ministries:\"The Porch\" AND topics:\"Books of the Bible\""}'
          limit: 5
    type: ActionList
    subtitle: Books of the Bible
    primaryAction:
      action: OPEN_CHANNEL
      title: 'View More'
      relatedNode:
        __typename: ContentChannel
        id: '{"search":"porchapp_production_messages_force_ranked","name":"Books of the Bible","query":"topic_books_of_the_bible","filters":"ministries:\"The Porch\" AND topics:\"Books of the Bible\""}'
        name: Books of the Bible
  - algorithms:
      - type: CONTENT_CHANNEL_CHILDREN
        arguments:
          id: '{"search":"porchapp_production_messages_force_ranked","name":"Sex","query":"topic_sex","filters":"ministries:\"The Porch\" AND topics:\"Sex\""}'
          limit: 5
    type: HorizontalCardList
    subtitle: Sex
    primaryAction:
      action: OPEN_CHANNEL
      title: 'View More'
      relatedNode:
        __typename: ContentChannel
        id: '{"search":"porchapp_production_messages_force_ranked","name":"Sex","query":"topic_sex","filters":"ministries:\"The Porch\" AND topics:\"Sex\""}'
        name: Sex
  - algorithms:
      - type: CONTENT_CHANNEL_CHILDREN
        arguments:
          id: '{"search":"porchapp_production_messages_force_ranked","name":"Culture","query":"topic_culture","filters":"ministries:\"The Porch\" AND topics:\"Culture\""}'
          limit: 5
    type: HorizontalCardList
    subtitle: Culture
    primaryAction:
      action: OPEN_CHANNEL
      title: 'View More'
      relatedNode:
        __typename: ContentChannel
        id: '{"search":"porchapp_production_messages_force_ranked","name":"Culture","query":"topic_culture","filters":"ministries:\"The Porch\" AND topics:\"Culture\""}'
        name: Culture
  - algorithms:
      - type: CONTENT_CHANNEL_CHILDREN
        arguments:
          id: '{"search":"porchapp_production_messages_force_ranked","name":"Money","query":"topic_money","filters":"ministries:\"The Porch\" AND topics:\"Money\""}'
          limit: 5
    type: HorizontalCardList
    subtitle: Money
    primaryAction:
      action: OPEN_CHANNEL
      title: 'View More'
      relatedNode:
        __typename: ContentChannel
        id: '{"search":"porchapp_production_messages_force_ranked","name":"Money","query":"topic_money","filters":"ministries:\"The Porch\" AND topics:\"Money\""}'
        name: Money
  - algorithms:
      - type: CONTENT_CHANNEL_CHILDREN
        arguments:
          id: '{"search":"porchapp_production_messages_force_ranked","name":"Work & Career","query":"topic_work_career","filters":"ministries:\"The Porch\" AND topics:\"Work & Career\""}'
          limit: 5
    type: HorizontalCardList
    subtitle: Work & Career
    primaryAction:
      action: OPEN_CHANNEL
      title: 'View More'
      relatedNode:
        __typename: ContentChannel
        id: '{"search":"porchapp_production_messages_force_ranked","name":"Work & Career","query":"topic_work_career","filters":"ministries:\"The Porch\" AND topics:\"Work & Career\""}'
        name: Work & Career
  - algorithms:
      - type: CONTENT_CHANNEL_CHILDREN
        arguments:
          id: '{"search":"porchapp_production_messages_force_ranked","name":"Faith","query":"topic_faith","filters":"ministries:\"The Porch\" AND topics:\"Faith\""}'
          limit: 5
    type: HorizontalCardList
    subtitle: Faith
    primaryAction:
      action: OPEN_CHANNEL
      title: 'View More'
      relatedNode:
        __typename: ContentChannel
        id: '{"search":"porchapp_production_messages_force_ranked","name":"Faith","query":"topic_faith","filters":"ministries:\"The Porch\" AND topics:\"Faith\""}'
        name: Faith

# apollos-church-api: { Faith: 207,
# apollos-church-api:   'Books of the Bible': 116,
# apollos-church-api:   Culture: 54,
# apollos-church-api:   Anxiety: 35,
# apollos-church-api:   Sex: 19,
# apollos-church-api:   Money: 14,
# apollos-church-api:   'Work & Career': 8 }


# Default mapping of field types -> ids. There's probably no reason to edit this.
ROCK_CONSTANTS:
  TEXT: 1
  MULTI_SELECT: 2
  BOOLEAN: 3
  COLOR: 4
  SINGLE_SELECT: 6
  INTEGER: 7
  PAGE_REFERENCE: 8
  IMAGE: 10
  DATE: 11
  DECIMAL: 14
  DEFINED_TYPE: 15
  DEFINED_VALUE: 16
  PERSON: 18
  HTML: 20
  MEMO: 21
  GROUP_TYPES: 22
  GROUP: 23
  CAMPUSES: 26
  ENTITY_TYPE: 29
  CAMPUS: 30
  EMAIL_TEMPLATE: 31
  FILE: 32
  GROUP_TYPE: 33
  KEY_VALUE_LIST: 34
  BINARY_FILE_TYPE: 35
  WORKFLOW_TYPE: 36
  BINARY_FILE: 37
  FINANCIAL_ACCOUNT: 38
  FINANCIAL_ACCOUNTS: 39
  COMPONENT: 40
  COMPONENTS: 41
  CATEGORIES: 42
  GROUP_ROLE: 43
  CATEGORY: 44
  LOCATION: 45
  DATE_RANGE: 46
  DECIMAL_RANGE: 47
  INTEGER_RANGE: 48
  TIME: 49
  GROUP_LOCATION_TYPE: 50
  CODE_EDITOR: 51
  PERSON_BADGES: 52
  SITE: 53
  COMMUNICATION_TEMPLATE: 54
  DAY_OF_WEEK: 55
  DAYS_OF_WEEK: 56
  REMOTE_AUTHS: 57
  COMPARISON: 58
  METRIC_ENTITY: 59
  WORKFLOW_ACTIVITY: 60
  WORKFLOW_ATTRIBUTE: 61
  METRICS: 62
  ENTITY: 63
  METRIC_CATEGORIES: 64
  WORKFLOW_TEXT_OR_ATTRIBUTE: 65
  SLIDING_DATE_RANGE: 66
  GROUP_TYPE_GROUP: 67
  SECURITY_ROLE: 68
  VALUE_LIST: 69
  CURRENCY: 70
  EMAIL: 71
  URL_LINK: 72
  WORKFLOW_TYPES: 73
  ATTRIBUTE: 74
  SCHEDULES: 75
  CONTENT_CHANNEL: 76
  AUDIO_FILE: 77
  AUDIO_URL: 78
  VIDEO_FILE: 79
  VIDEO_URL: 80
  ENCRYPTED_TEXT: 81
  FILTER_DATE: 82
  DATE_TIME: 83
  DEFINED_VALUE_RANGE: 84
  RATING: 85
  SYSTEM_EMAIL: 86
  FINANCIAL_GATEWAY: 87
  GROUP_AND_ROLE: 88
  NOTE_TYPE: 89
  NOTE_TYPES: 90
  EVENT_CALENDAR: 91
  EVENT_ITEM: 92
  CONNECTION_ACTIVITY_TYPE: 93
  CONNECTION_OPPORTUNITY: 94
  CONNECTION_REQUEST: 95
  CONNECTION_STATE: 96
  CONNECTION_STATUS: 97
  CONNECTION_TYPE: 98
  CONNECTION_TYPES: 99
  MERGE_TEMPLATE: 100
  RANGE_SLIDER: 101
  BINARY_FILE_TYPES: 102
  MARKDOWN: 103
  DATA_VIEW: 104
  PHONE_NUMBER: 105
  SCHEDULE: 106
  LAVA_COMMANDS: 107
  ADDRESS: 108
  BENEVOLENCE_REQUEST: 109
  CONTENT_CHANNEL_TYPES: 110
  WORKFLOW: 111
  SSN: 112
  MATRIX: 113
  LAVA: 114
  DATA_VIEWS: 115
  COMMUNICATION_PREFERENCE: 116
  INTERACTION_CHANNEL: 117
  GROUP_MEMBER: 118
  TIME_ZONE: 119
  LABEL: 120
